### ISSUE TITLE
Add Support for THM Throwback VPN Troubleshooting

### ISSUE THREAD

**Issue by CMNatic** [tryhackme/openvpn-troubleshooting#1]
At the moment the THM VPN Troubleshooting script does not check for connectivity for users of the THM Throwback VPN. This results in the error message "Something went wrong" even if their connection to the Throwback VPN is working fine or not.

![image](https://user-images.githubusercontent.com/4163116/92902961-9dfa2e80-f419-11ea-895c-bf63200fe00d.png)

**Comment by MuirlandOracle** [comment]
Changed the IP Regex to support this in commit b1eb5d5bb78785ce3b117b6140c841ab78678dee. This should fix the issue -- thanks CMN :)
