### ISSUE TITLE
Line8 Colour

### ISSUE THREAD

**Issue by GitHubBub2022** [tryhackme/openvpn-troubleshooting#5]
getting this error ┌──(root💀kali)-[/home/thomas/Downloads]
└─# python3 thm-troubleshoot   
  File "/home/thomas/Downloads/thm-troubleshoot", line 8
    colour(){

**Comment by shadow-absorber** [comment]
the script is a bash shell script and not a python script... you are trying to run it with python3 that will obviously fail due to bash and python3 not being the same thing @GitHubBub2022
