### ISSUE TITLE
thm-troubleshoot: command not found

### ISSUE THREAD

**Issue by zpoppy1** [tryhackme/openvpn-troubleshooting#6]
└─# sudo thm-troubleshoot
thm-troubleshoot: command not found

i have no idea

**Comment by shadow-absorber** [comment]
@zpoppy1 for you to be able to run a script or command or file from the same dir you need `sudo ./thm-troubleshoot`
or you could specify the full path like `sudo /home/user/Downloads/thm-troubleshoot` for it to work for you
