### ISSUE TITLE
No option to terminate the connection 

### ISSUE THREAD

**Issue by SeaLi-oN** [tryhackme/openvpn-troubleshooting#7]
i am by default using the Troubleshooting script to establish the VPN connection, but as far as i know, there's no way to terminate it unless i reboot the system

Disclaimer:
maybe there is a way, I am unfamiliar with OpenVPN

**Comment by shadow-absorber** [comment]
`sudo killall openvpn` will kill the vpn connect the easy way
alternatively if you really wanna force it you can use
`sudo killall -9 openvpn` which will run sigkill instead of sigterm
@SeaLi-oN

**Comment by SeaLi-oN** [comment]
> `sudo killall openvpn` will kill the vpn connect the easy way
> 
> alternatively if you really wanna force it you can use
> 
> `sudo killall -9 openvpn` which will run sigkill instead of sigterm
> 
> @SeaLi-oN 

Thanks 😀😀

**Comment by shadow-absorber** [comment]
no problem
